hue-remote-api:
  base-url: ${HUE_REMOTE_API_BASE_URL}
  client-id: ${HUE_REMOTE_API_CLIENT_ID}
  client-secret: ${HUE_REMOTE_API_CLIENT_SECRET}

entsoe-api:
  base-url: ${ENTSOE_API_BASE_URL}
  security-token: ${ENTSOE_API_SECURITY_TOKEN}

fingrid-api:
  base-url: ${FINGRID_API_BASE_URL}
  api-key: ${FINGRID_API_KEY}

dynamodb:
  electricity-prices:
    table-name: ${ELECTRICITY_PRICES_DYNAMODB_TABLE_NAME}
  hue-users:
    table-name: ${HUE_USERS_DYNAMODB_TABLE_NAME}
